GET http://localhost:4000/api/cloudant

###

POST http://localhost:4000/api/cloudant
content-type: application/json

{
    "name": "sample",
    "message": "Hello world"
}

###

GET http://localhost:4000/api/cloudant/123
###

PATCH http://localhost:4000/api/cloudant/123
content-type: application/json

{
    "name": "sample",
    "message": "Hello world!!"
}

###

DELETE http://localhost:4000/api/cloudant/123
content-type: application/json
