GET http://localhost:4000/api/cloudant

###

POST http://localhost:4000/api/cloudant
content-type: application/json

{
    "name": "sample",
    "message": "Awesome Cloud Workshop"
}

###

GET http://localhost:4000/api/cloudant/:id

###

PATCH http://localhost:4000/api/cloudant/:id
content-type: application/json

{
    "name": "sample",
    "message": "Awesome Cloud Workshop v2"
}

###

DELETE http://localhost:4000/api/cloudant/:id
content-type: application/json
